# Easy e-Invoice API - Cloudflare Workers Configuration
name = "easy-e-invoice-api"
main = "src/index-minimal.ts"
compatibility_date = "2024-08-16"
compatibility_flags = ["nodejs_compat"]

# Default development configuration
[vars]
ENVIRONMENT = "development"
API_VERSION = "v1"
LOG_LEVEL = "debug"
CORS_ORIGINS = "http://localhost:3000"
RATE_LIMIT_REQUESTS = "1000"
RATE_LIMIT_WINDOW = "60"
JWT_EXPIRY = "86400"
MAGIC_LINK_EXPIRY = "900"
FILE_UPLOAD_MAX_SIZE = "52428800"
PAGINATION_DEFAULT_LIMIT = "20"
PAGINATION_MAX_LIMIT = "100"

# Production Environment Configuration
[env.production]
name = "easy-e-invoice-api-prod"
# Custom domain routing can be added later
usage_model = "standard"

[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "v1"
LOG_LEVEL = "info"
CORS_ORIGINS = "https://easyeinvoice.com.my,https://www.easyeinvoice.com.my"
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "900"
JWT_EXPIRY = "86400"
MAGIC_LINK_EXPIRY = "900"
FILE_UPLOAD_MAX_SIZE = "52428800"
PAGINATION_DEFAULT_LIMIT = "20"
PAGINATION_MAX_LIMIT = "100"
ENABLE_ANALYTICS = "true"
ENABLE_MONITORING = "true"

# Production Green Environment Configuration (for Blue-Green Deployment)
[env.production-green]
name = "easy-e-invoice-api-prod-green"
usage_model = "standard"

[env.production-green.vars]
ENVIRONMENT = "production"
API_VERSION = "v1"
LOG_LEVEL = "info"
CORS_ORIGINS = "https://easyeinvoice.com.my,https://www.easyeinvoice.com.my"
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "900"
JWT_EXPIRY = "86400"
MAGIC_LINK_EXPIRY = "900"
FILE_UPLOAD_MAX_SIZE = "52428800"
PAGINATION_DEFAULT_LIMIT = "20"
PAGINATION_MAX_LIMIT = "100"
ENABLE_ANALYTICS = "true"
ENABLE_MONITORING = "true"

# Same KV namespaces as production (shared)
[[env.production-green.kv_namespaces]]
binding = "CACHE"
id = "765e2a2b8f484107b1aa1d496d864656"

[[env.production-green.kv_namespaces]]
binding = "SESSIONS"
id = "ea977be93eaf43a7b6ad4821ab9472ec"

[[env.production-green.kv_namespaces]]
binding = "RATE_LIMITS"
id = "ed9d94eb872742a9b4b38a4ffaf922a8"

# Same R2 buckets as production (shared)
[[env.production-green.r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "easy-einvoice-files-prod"

[[env.production-green.r2_buckets]]
binding = "BACKUP_STORAGE"
bucket_name = "easy-einvoice-backups-prod"

# Analytics Engine for Production Green
[[env.production-green.analytics_engine_datasets]]
binding = "API_ANALYTICS"

# Staging Environment Configuration
[env.staging]
name = "easy-e-invoice-api-staging"
route = { pattern = "api-staging.easyeinvoice.com.my/*", zone_name = "easyeinvoice.com.my" }

[env.staging.vars]
ENVIRONMENT = "staging"
API_VERSION = "v1"
LOG_LEVEL = "debug"
CORS_ORIGINS = "https://staging.easyeinvoice.com.my"
RATE_LIMIT_REQUESTS = "200"
RATE_LIMIT_WINDOW = "900"
JWT_EXPIRY = "86400"
MAGIC_LINK_EXPIRY = "900"
FILE_UPLOAD_MAX_SIZE = "52428800"
PAGINATION_DEFAULT_LIMIT = "20"
PAGINATION_MAX_LIMIT = "100"
ENABLE_ANALYTICS = "true"
ENABLE_MONITORING = "true"

# KV Namespaces for Production
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "765e2a2b8f484107b1aa1d496d864656"

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "ea977be93eaf43a7b6ad4821ab9472ec"

[[env.production.kv_namespaces]]
binding = "RATE_LIMITS"
id = "ed9d94eb872742a9b4b38a4ffaf922a8"

# KV Namespaces for Staging
[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "cache_staging_id_placeholder"

[[env.staging.kv_namespaces]]
binding = "SESSIONS"
id = "sessions_staging_id_placeholder"

[[env.staging.kv_namespaces]]
binding = "RATE_LIMITS"
id = "rate_limits_staging_id_placeholder"

# R2 Storage Buckets
[[env.production.r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "easy-einvoice-files-prod"

[[env.production.r2_buckets]]
binding = "BACKUP_STORAGE"
bucket_name = "easy-einvoice-backups-prod"

[[env.staging.r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "easy-einvoice-files-staging"

# Analytics Engine for Production
[[env.production.analytics_engine_datasets]]
binding = "API_ANALYTICS"

[[env.staging.analytics_engine_datasets]]
binding = "API_ANALYTICS"


# Build Configuration - removed to prevent recursive builds


# Required Secrets (set using wrangler secret put):
# - DATABASE_URL: PostgreSQL connection string
# - JWT_SECRET: Secret for JWT token signing
# - RESEND_API_KEY: Email service API key
# - SENTRY_DSN: Error tracking DSN (optional)
# - STRIPE_SECRET_KEY: Payment processing (optional)
# - LHDN_API_KEY: MyInvois integration (optional)